markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

repository: https://github.com/apache/orc
jira: https://issues.apache.org/jira/browse
dist: https://dist.apache.org/repos/dist/release/orc
dist_mirror: https://www.apache.org/dyn/closer.cgi/orc
tag_url: https://github.com/apache/orc/releases/tag/rel
dist_archive: https://archive.apache.org/dist/orc
destination: target
exclude: [README.md, Gemfile*]
keep_files: [.git]
highlight_color: "#67cf56"

collections:
  docs:
    output: true
